### ISSUE TITLE
Error when decoding .rbxlx file

### ISSUE THREAD

**Issue by Bluejutzu** [rojo-rbx/rbxlx-to-rojo#95]
```shell
White attempting to decode the place file, at line 292344, column B: Unexpected XML events StartElement(AcausticAbsorption, {"": "", "xnime": "https://www.w3.org/2005/05/xmlnime", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns", "xsi": "http://www.w3.org/2001/XMLSchema-instance}) rblx_xml didn't know what to do
```

**Comment by Placewith5s** [comment]
File format: .rbxl

An error occurred while using rbxlx-to-rojo.
While attempting to decode the place file, at Decompression failed. Input invalid or too long? rbx_binary didn't know what to do

**Comment by R0IE** [comment]
got same issue

**Comment by Andaroth** [comment]
I encounter the same problem.
Here is a more complete log, hope this will help to track the issue better. 

```
[2025-10-02T00:40:55Z INFO  rbxlx_to_rojo] rbxlx-to-rojo 1.0.1
[2025-10-02T00:40:55Z INFO  rbxlx_to_rojo] Select a place file.
[2025-10-02T00:40:55Z INFO  rbxlx_to_rojo] Opening place file
[2025-10-02T00:40:55Z INFO  rbxlx_to_rojo] Decoding place file, this is the longest part...
[2025-10-02T00:40:55Z WARN  rbx_xml::deserializer] Unknown value type name "SecurityCapabilities" in Roblox XML model file. Found in property Workspace.Capabilities.
[2025-10-02T00:40:55Z WARN  rbx_xml::deserializer] Unknown value type name "UniqueId" in Roblox XML model file. Found in property Workspace.HistoryId.
[2025-10-02T00:40:55Z WARN  rbx_xml::deserializer] Unknown value type name "OptionalCoordinateFrame" in Roblox XML model file. Found in property Workspace.WorldPivotData.
An error occurred while using rbxlx-to-rojo.
While attempting to decode the place file, at line 202233, column 5: Unexpected XML event StartElement(AcousticAbsorption, {"": "", "xmime": "http://www.w3.org/2005/05/xmlmime", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/", "xsi": "http://www.w3.org/2001/XMLSchema-instance"}) rbx_xml didn't know what to do
```

In my document, line 202233 is the following: `<AcousticAbsorption>1</AcousticAbsorption>` and it is child of some `MaterialVariant`.

EDIT: When I remove all the `MaterialVariant` elements the script does not fail and I'm able to open the project in my IDE then. 
I note that in the past when I published my project on Roblox I had some warnings with my textures, maybe you can try to publish your game in Studio and verify your logs in Output panels to see if you have some warning or errors that might also cause this error to occur.

Hope this helps you guys.

**Comment by Taveple** [comment]
> EDIT: When I remove all the `MaterialVariant` elements the script does not fail and I'm able to open the project in my IDE then. I note that in the past when I published my project on Roblox I had some warnings with my textures, maybe you can try to publish your game in Studio and verify your logs in Output panels to see if you have some warning or errors that might also cause this error to occur.
> 
> Hope this helps you guys.


Thank you for the suggestion. I was still experiencing issues even after removing the material variant. I think I have found a solution that is fool proof for the history of this and that is to simply remove everything that is not a folder, module script, and local/server script.

If you have anything in workspace, delete it. Lighting, delete it. etc. before clicking file > save as. You only need the code anyways and it removes the entire file size worth of models. Hope this helps

**Comment by Taveple** [comment]
I turned it into a step-by-step   v

How to port a project into Rojo 2025:

1. Open your game

2. File > Download a Copy

3. Open the copy

4. Remove children under sections that are NOT: ReplicatedStorage, ServerStorage, ServerScriptService, StarterPlayerScripts, (StarterCharacterScripts?)

5. File > Save As > .rbxlx

6. Run the rbxlx-to-rojo.exe file - if experiencing issues, run it in the command prompt like so: cmd /k C:\Path\To\rbxlx-to-rojo.exe

(make sure to change your path to find your folders 😉)

**Comment by Lyzrinn** [comment]
For anybody coming across this, I have a better solution. 

1. Open the RBXLX on your favorite text editor (notepad ++ works fine)
2. Search for `<AcousticAbsorption>1</AcousticAbsorption>` (or any occurrences of acoustic absorption, the value may differ if you messed with the new acoustic absorption update fromroblox)
3. Replace all of the matches with an empty character or a space
4. Save
5. Run the rbxlx-to-rojo.exe file, select your file, wait a while (depending on project size) and everything should be working as expected.

This only works with RBXLX file as this is an XML file that can be edited.
